example/example/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.http import  HttpResponse
from django.conf import settings
from django.conf.urls.static import static

# def index(request):
#     return HttpResponse('Hello this is my first view')

# def dynamic_view(request, name):
#     return HttpResponse(f'Hello {name}')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('auth/', include('auth_user.urls')),
    # path('', index),
    # path('<str:name>', dynamic_view)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/home/urls.py
from django.urls import path
from home.views import delete_profile_picture, edit_book, get_view, index, detail_book_view, display, add_book, post_book, profile, delete_book, profile_picture

urlpatterns = [
    path('', index, name='home'),
    path('book/<int:pk>', detail_book_view, name='detail_book'), # yo name chai href url ma use hunxa
    path('get_view', get_view, name='get_view'),
    path('display', display, name='display'),
    path('add_book', add_book, name='add_book'),
    path('post_book', post_book, name='post_book'),
    path('user/<str:username>', profile, name='profile'),
    path('edit_book/<int:pk>', edit_book, name='edit_book'),
    path('delete_book/<int:pk>', delete_book, name='delete_book'),
    path('profile_picture', profile_picture, name='profile_picture'),
    path('delete_profile_picture', delete_profile_picture, name='delete_profile_picture'),

]

example/home/models.py
from django.db import models
from django.contrib.auth.models import User
from auth_user.models import Author

# Create your models here.
class Book(models.Model):
    name = models.CharField(max_length=50)
    price = models.FloatField()
    desc = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self) -> str:
        return self.name

example/templates/add_book.html
{% extends 'base.html' %}
{% block head %}
    <title>Add Book</title>
{% endblock head %}
{% block body %}
<div class="container">
    <h3>Add Book</h3>
    <form action="{% url 'post_book' %}" method="post">
        {% csrf_token %}
        {{form.as_p}} <!-- form mathra lekhda horizontally aauxa 
                            ani .as_p use garyo vane paragraph ko tarikale aauxa -->


        {% comment %} <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Name</label>
            <input type="text" name="book_name" class="form-control" id="exampleFormControlInput1">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Price</label>
            <input type="number" name="price" class="form-control" id="exampleFormControlInput1">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Description</label>
            <textarea name="desc" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div> {% endcomment %}
        <button class="btn btn-success">
            Add Book
        </button>
    </form>
</div>
{% endblock body %}

example/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    {% block head %}{% endblock head %}
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Our Books</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home </a>
        </li>
        <li class="nav-item active">
            {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'add_book' %}">Add Book </a>
            {% endif %}
        </li>
        <li class="nav-item active">
            {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'profile' request.user.username %}">Profile </a>
            {% endif %}
        </li>
        <li class="nav-item active">
            {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="nav-link" href="{% url 'login_view' %}">Login</a>
            {% endif %}
        </li>
        <li class="nav-item active">
            {% if request.user.is_authenticated %}
                
            {% else %}
                <a class="nav-link" href="{% url 'register_view' %}">Register</a>
            {% endif %}
        </li>
        {% comment %} <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
        </li> {% endcomment %}
        </ul>
        {% comment %} <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> {% endcomment %}
    </div>
    </nav>
    {% block body %}{% endblock body %}
</body>
</html>

example/templates/delete_book.html
{% extends 'base.html' %}
{% block head %}
    <title>Delete Book</title>
{% endblock head %}
{% block body %}
    <div class="container">
        <h1>
            Are you sure you want to delete the Book?
        </h1>
        <h3>
            Name: {{book.name}}
        </h3>

        <form method='post'>
            {% csrf_token %}
            <button class='btn btn-danger'>Delete</button>
        </form>
    </div>
{% endblock body %}

example/templates/detail_book.html
{% extends 'base.html' %}
{% block head %}
<title>Book Details</title>
{% endblock head %}
{% block body %}
    <div class="container">
        {% comment %} <a href='{% url 'home' %}'>Home</a> {% endcomment %}
        {% if request.user.is_authenticated %}
            <a href="{% url 'edit_book' book.pk %}" class="btn btn-danger float-end">Edit Book</a>
        {% endif %}
        <h3>{{book}}</h3>
        <h4>{{book.price}}</h4>
        <p>{{book.desc}}</p>
        Written by: <a href='{% url 'profile' book.author %}'>{{book.author}}</a>
    </div>
{% endblock body %}

example/templates/edit_book.html
{% extends 'base.html' %}
{% block head %}
    <title>Edit Book</title>
{% endblock head %}
{% block body %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{form}}
            <br>
            <button class='btn-primary'>Edit Book</button>
        </form>
    </div>
{% endblock body %}

example/templates/get.html
{% comment %} learing get & post in django {% endcomment %}

<form action="{% url 'display' %}" method="get">
    <input type="text" name="get_name">
    <button>Click Here for Get Request</button>
</form>

<form action="{% url 'display' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="get_name">
    <button>Click Here for Post Request</button>
</form>

example/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<title>My home page</title>
<link rel="stylesheet" href='{% static 'css/style.css' %}'>
{% endblock head %}
{% block body %}
<!--    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Our Books</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-link" href="{% url 'login_view' %}">Login</a>
            {% endif %}
        </li>
        {% comment %} <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
        </li> {% endcomment %}
        </ul>
        {% comment %} <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> {% endcomment %}
    </div>
    </nav>
-->
    <div class="container">
        {% comment %} {% if request.user.is_authenticated %}
        <a href="{% url 'add_book' %}" class="btn btn-danger float-end">Add Book</a>
        {% endif %} {% endcomment %}
        <h1>All books</h1>
        {% for book in books %}
            name:
            <a href='{% url 'detail_book' book.pk %}'> <!--Normal  tarika jasto url nalekhnu-->
                {{book.name}}
            </a>
            <br>
            {% if book.price > 1200 %}
            <button>Book is not cheap</button>
            {% else %}
            <button>Book is cheap</button>
            {% endif %}
            price: {{book.price}}
            <br>
            author: {{book.author}}
            <br>
            desc: {{book.desc}}
            <br>
            <br>
        {% endfor %}
    </div>
{% endblock body %}

example/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>{{request.user}}</title>
{% endblock head %}
{% block body %}

<div class="container">
    <h1>
        {{author}}
    </h1>
    {% if author.profile_pic %}
        <img src='{{author.profile_pic.url}}' alt="" height = '100'>

        <form action='{% url 'profile_picture' %}' enctype='multipart/form-data' method="post">
            {% csrf_token %}
            <input type="file" accept="image/*" name="pic">
            <br>
            <button class="btn btn-dark">Update Profile Picture</button>
        </form>
        <form action='{% url 'delete_profile_picture' %}'>
            {% csrf_token %}
            <button class="btn btn-danger">Delete Profile Picture</button>
        </form>
    {% else %}
        <img src={% static 'images/default_profile_pic.png' %} alt="Profile Pic" height='100'>

        <form action='{% url 'profile_picture' %}' enctype='multipart/form-data' method="post">
            {% csrf_token %}
            <input type="file" accept="image/*" name="pic">
            <br>
            <button class="btn btn-dark">Add Profile Picture</button>
        </form>
    {% endif %}
    <br>
    
    {% for book in author.book_set.all %}
        <a href='{% url 'detail_book' book.pk  %}'>
            <h5>
                {{book}}
            </h5>
        </a>
        {% if request.user.is_authenticated %}
            <a href='{% url 'edit_book' book.pk %}'>Edit Book</a>
            ~~~
            <a href='{% url 'delete_book' book.pk %}'>Delete Book</a>
        {% endif %}
        <br>
        <br>
    {% endfor %}
</div>

{% endblock body %}